[project]
name = "simple-python-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "pyarrow>=19.0.0",
]

[project.scripts]
hello = "hello.cli:main"